name: Release

on:
  release:
    types: [published]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.2.0
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Clear existing docker image cache
        run: docker image prune -af

      - name: Run Gradle Build
        run: ./gradlew build --scan --no-daemon -i -x test

      - name: Run Gradle Publish
        run: |
          ./gradlew publish \
            -Pversion="${{github.event.release.tag_name}}" --scan --no-daemon -i
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
